POST http://localhost:8080/users/signup HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXMyQGdtYWlsLmNvbSIsImV4cCI6MTU0MTAwMDA3NH0.w2Iwm1yEGf6nGGE0McKgLV6QYSOLAJz7WE7pfjRmWdxLGvFuhWK99XPawdI7UMRZZJwV7AjezeUdSI-yzaRAyA

{
    "firstName":"D",
    "lastName":"Kitaw",
    "email":"tes7@gmail.com",
    "password":"1239",
    "addresses":[
        {
            "city":"Silver Spring",
            "county":"USA",
            "streetName":"123 Street name",
            "postalCode":"ABDC",
            "type":"billing"
        },
        {
            "city":"Silver Spring",
            "county":"USA",
            "streetName":"123 Street name",
            "postalCode":"ABDC",
            "type":"shipping"
        }
    ]   
}

###
http://localhost:8080/users/3Q3egEYEYQe4unSpLoRhUHiz17PRIm
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXMyQGdtYWlsLmNvbSIsImV4cCI6MTU0MTAwMDA3NH0.w2Iwm1yEGf6nGGE0McKgLV6QYSOLAJz7WE7pfjRmWdxLGvFuhWK99XPawdI7UMRZZJwV7AjezeUdSI-yzaRAyA