POST http://localhost:8080/users HTTP/1.1
content-type: application/json

{
    "firstName":"D",
    "lastName":"Kitaw",
    "email":"tes3@gmail.com",
    "password":"1239",
    "addresses":[
        {
            "city":"Silver Spring",
            "county":"USA",
            "streetName":"123 Street name",
            "postalCode":"ABDC",
            "type":"billing"
        },
        {
            "city":"Silver Spring",
            "county":"USA",
            "streetName":"123 Street name",
            "postalCode":"ABDC",
            "type":"shipping"
        }
    ]   
}
