
POST http://localhost:8080/users/login HTTP/1.1
content-type: application/json

{
    "email":"a1@gmail.com",
    "password":"1234"
}


###
http://localhost:8080/users?page=3&limit=5
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhMUBnbWFpbC5jb20iLCJleHAiOjE1NDA5MzIwNzh9.3bxqD30IEOYAoRJe5Q2vtyS7Yf3CgvwApOeqfEhgzBqC8Yy3adgzHdjWYZmaBbioJIob2qJe_D17c39twxGW0w
###
http://localhost:8080/users/uTYBcRqCkpO2ObGmQ19HoTOOTqu4uR
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhMUBnbWFpbC5jb20iLCJleHAiOjE1NDA5MzIwNzh9.3bxqD30IEOYAoRJe5Q2vtyS7Yf3CgvwApOeqfEhgzBqC8Yy3adgzHdjWYZmaBbioJIob2qJe_D17c39twxGW0w